### ISSUE TITLE
Option to use custom prefix to label

### ISSUE THREAD

**Issue by anshulsahni** [adamzolyak/monorepo-pr-labeler-action#14]
Currently there in addition to "repository/package name" there is only one option of prefix to label that also hard-coded in the code﻿ here :point_right: [master/app.js#L53](https://github.com/adamzolyak/monorepo-pr-labeler-action/blob/master/app.js#L53)

In place of this if give the user of the action an option to specify the prefix specified to action with the help `with` parameter
```
- name: Label PR
  uses: adamzolyak/monorepo-pr-labeler-action
  with:
     labelPrefix: package:
```
